/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ttt;

import java.net.*;
import java.io.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws MalformedURLException,IOException,ProtocolException {
      URL url = new URL("https://www.google.com");
      HttpURLConnection con = (HttpURLConnection) url.openConnection();
      con.setRequestMethod("GET");
      System.out.println("Done!");
    }
}
